# Generated by Django 5.1.4 on 2024-12-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='difficulty',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='question_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
